# Generated by Django 2.2.17 on 2021-03-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedOnApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='job_id',
        ),
    ]
