# Generated by Django 2.2.17 on 2021-03-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedOnApp', '0002_userprofile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
